
cc.Class({
    extends: cc.Component,

    properties: {

    },
    start () {
        // this.animCtrl = this.node.getComponent(cc.Animation);
        // this.animCtrl.play('SparklersAnim');
        // this.animCtrl.on('stop', this.onAnimStop, this);
    },
    onAnimStop: function()
    {
        // cc.director.loadScene("Login");
        // this.node.runAction(cc.blink(1.0));
        // var scene=CreateScene('Login');
        // var transition=new cc.TransitionCrossFade(1,scene);
        // cc.director.runScene(transition);
        cc.director.loadScene('Login');
    }
});
